// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xirvebryfcwncnhhtbqo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhpcnZlYnJ5ZmN3bmNuaGh0YnFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMTczNTAsImV4cCI6MjA2ODY5MzM1MH0.GPAHmepEQGpzmIi7HU1DGl8Afoh5qf60sgaTfv1obd4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});